CREATE INDEX NOME_IDX ON AUTORES (NOME);
CREATE INDEX NOME_IDX ON EDITORAS (NOME);
CREATE INDEX TITULO_IDX ON LIVROS (TITULO);
CREATE INDEX ISBN_IDX ON LIVROS (ISBN);
CREATE INDEX NOME_IDX ON BIBLIOTECAS (NOME);
CREATE INDEX EXEMPLARES_IDX ON BIBLIOTECAS_LIVROS (EXEMPLARES);