/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene;

/**
Builder class for javafx.scene.Parent
@see javafx.scene.Parent
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public abstract class ParentBuilder<B extends javafx.scene.ParentBuilder<B>> extends javafx.scene.NodeBuilder<B> {
    protected ParentBuilder() {
    }
    
    
    private int __set;
    public void applyTo(javafx.scene.Parent x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setImpl_traversalEngine(this.impl_traversalEngine);
        if ((set & (1 << 1)) != 0) x.getStylesheets().addAll(this.stylesheets);
    }
    
    private com.sun.javafx.scene.traversal.TraversalEngine impl_traversalEngine;
    /**
    Set the value of the {@link javafx.scene.Parent#getImpl_traversalEngine() impl_traversalEngine} property for the instance constructed by this builder.
    @treatAsPrivate
    @deprecated This is an internal API that is not intended for use and will be removed in the next version
    */
    @SuppressWarnings("unchecked") @Deprecated
    public B impl_traversalEngine(com.sun.javafx.scene.traversal.TraversalEngine x) {
        this.impl_traversalEngine = x;
        __set |= 1 << 0;
        return (B) this;
    }
    
    private java.util.Collection<? extends java.lang.String> stylesheets;
    /**
    Add the given items to the List of items in the {@link javafx.scene.Parent#getStylesheets() stylesheets} property for the instance constructed by this builder.
    * @since JavaFX 2.1
    */
    @SuppressWarnings("unchecked")
    public B stylesheets(java.util.Collection<? extends java.lang.String> x) {
        this.stylesheets = x;
        __set |= 1 << 1;
        return (B) this;
    }
    
    /**
    Add the given items to the List of items in the {@link javafx.scene.Parent#getStylesheets() stylesheets} property for the instance constructed by this builder.
    * @since JavaFX 2.1
    */
    public B stylesheets(java.lang.String... x) {
        return stylesheets(java.util.Arrays.asList(x));
    }
    
}
